name: macOS Build
on:
  push:
    branches:
      - main

jobs:
  install_dependencies_and_build:
    name: Install Dependencies and Build
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew install GraphicsMagick webp cmake
          brew install ffmpeg jpeg-turbo libexif
          brew install pandoc
          brew unlink jpeg
          brew link --force jpeg-turbo
      - name: Get the Source
        uses: actions/checkout@v2
      - name: Build timg
        run: |
          mkdir build
          cd build
          cmake .. -DWITH_VIDEO_DECODING=On -DWITH_VIDEO_DEVICE=On
          make -k
